#!/usr/bin/env python3
"""Build-time ClassDB cache generator for Godot release exports (TASK-0304).

In Godot release/export builds, ClassDB.class_exists() and ClassDB.get_class_list()
are stripped.  ControlReflector falls back to this generated cache so it can
still identify Control-derived node types and build the behavior dict correctly.

The script scans all .gd files in the project for "extends <ClassName>" and
"is <ClassName>" patterns, then emits a GDScript file with the discovered class
set plus a hardcoded base list of standard Godot Control classes.

Usage
-----
    python scripts/build/godot_cache_classdb.py
    python scripts/build/godot_cache_classdb.py \\
        --project fixtures/godot-test-project \\
        --adapter adapters/godot \\
        --out adapters/godot/addons/autoagent/runtime/class_db_cache.gd

Exit codes
----------
    0 — cache generated (or already up-to-date)
    1 — write error
    2 — usage / path error
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Standard Godot Control classes always included regardless of source scan.
BASELINE_CLASSES: list[str] = [
    "Node",
    "CanvasItem",
    "CanvasLayer",
    "Control",
    "Container",
    "BoxContainer",
    "HBoxContainer",
    "VBoxContainer",
    "PanelContainer",
    "MarginContainer",
    "ScrollContainer",
    "GridContainer",
    "TabContainer",
    "BaseButton",
    "Button",
    "CheckBox",
    "CheckButton",
    "MenuButton",
    "OptionButton",
    "TextureButton",
    "LinkButton",
    "Label",
    "RichTextLabel",
    "LineEdit",
    "TextEdit",
    "CodeEdit",
    "SpinBox",
    "HSlider",
    "VSlider",
    "ProgressBar",
    "TextureRect",
    "ColorRect",
    "NinePatchRect",
    "Panel",
    "Popup",
    "PopupMenu",
    "PopupPanel",
    "Window",
    "ItemList",
    "Tree",
    "GraphNode",
    "GraphEdit",
    "TabBar",
    "Separator",
    "HSeparator",
    "VSeparator",
    "VideoStreamPlayer",
]

# Regex patterns for extracting class names from GDScript source.
_EXTENDS_RE = re.compile(r"^extends\s+(\w+)", re.MULTILINE)
_IS_RE = re.compile(r"\bis\s+(\w+)", re.MULTILINE)


def scan_classes(search_paths: list[Path]) -> set[str]:
    """Return class names referenced across all .gd files in search_paths."""
    found: set[str] = set()
    for directory in search_paths:
        for gd_file in directory.rglob("*.gd"):
            try:
                src = gd_file.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            found.update(m.group(1) for m in _EXTENDS_RE.finditer(src))
            found.update(m.group(1) for m in _IS_RE.finditer(src))
    return found


def generate_cache(classes: set[str]) -> str:
    """Render the GDScript cache file content."""
    all_classes = sorted(set(BASELINE_CLASSES) | classes)
    lines = [
        "## Auto-generated by scripts/build/godot_cache_classdb.py — DO NOT EDIT.",
        "## Provides a fallback class list for release builds where ClassDB is stripped.",
        "## Regenerate: python scripts/build/godot_cache_classdb.py",
        "extends RefCounted",
        "",
        "const CACHED_CLASSES: PackedStringArray = [",
    ]
    for cls in all_classes:
        lines.append(f'\t"{cls}",')
    lines += [
        "]",
        "",
        "",
        "static func class_exists_cached(class_name: String) -> bool:",
        "\treturn class_name in CACHED_CLASSES",
        "",
        "",
        "static func get_cached_class_list() -> PackedStringArray:",
        "\treturn CACHED_CLASSES",
    ]
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="godot_cache_classdb",
        description="Generate class_db_cache.gd for Godot release export builds.",
    )
    p.add_argument(
        "--project",
        type=Path,
        default=REPO_ROOT / "fixtures" / "godot-test-project",
        help="Godot fixture project root to scan (default: fixtures/godot-test-project)",
    )
    p.add_argument(
        "--adapter",
        type=Path,
        default=REPO_ROOT / "adapters" / "godot",
        help="Godot adapter root to scan (default: adapters/godot)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "adapters" / "godot" / "addons" / "autoagent"
                 / "runtime" / "class_db_cache.gd",
        help="Output path for the generated cache file.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated content without writing.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    search_paths: list[Path] = []
    for p in (args.project, args.adapter):
        if p.is_dir():
            search_paths.append(p)
        else:
            print(f"WARNING: scan path not found, skipping: {p}", file=sys.stderr)

    scanned = scan_classes(search_paths)
    content = generate_cache(scanned)

    if args.dry_run:
        print(content)
        return 0

    try:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content, encoding="utf-8")
        print(f"Written {len(content.splitlines())} lines → {args.out}")
    except OSError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
